name: JumpPad
version: '1.0-SNAPSHOT'
main: fr.azenchire.jumppad.Main
api-version: '1.21'
authors: [ AzenChire ]
description: Launch players into the air when they step on special blocks like pressure plates!
website: https://discord.gg/4nzzkS8beg
commands:
  jumppad:
    description: JumpPad command
    usage: /jumppad reload
    permission: jumppad.reload
